name: Print Environments

on:
  push:
    branches:
      - main

jobs:
  print_environments:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environments
        run: |
          echo "Printing all environment variables:"
          env
