name: Print Environments

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  print_environments:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environments
        run: echo "The value of MY_VAR is ${{ vars.TESTING }}"
