name: Print Environments

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  TESTING: ${{ env.TESTING }}

jobs:
  print_environments:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environments
        run: echo "The value of MY_VAR is ${{ env.TESTING }}"
