name: Print Environments

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  print_environments:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'other' }}
    steps:
      - name: Print Environments
        run: echo "The value of MY_VAR is ${{ vars }} ${{ vars.TESTING }}"
